docker:
    host: ""
github:
    owner: manashmandal
    repo: ""
    scope: org
    token: ${GITHUB_TOKEN}
log_level: info
runner:
    env: {}
    image: myoung34/github-runner:latest
    labels:
        - gale
        - self-hosted
        - linux
        - x64
        - docker
    network_mode: ""
scaler:
    max_runners: 10
    min_runners: 2
    poll_interval: 10s
    scale_up_delay: 5s
